name: Build and Publish Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Premake5 via Winget
        run: winget install Premake.Premake.5.Beta

      - name: Run Premake5 with VS2022
        run: premake5 vs2022

      - name: Build Release with MSBuild
        run: |
          msbuild /p:Configuration=Release

      - name: Create Release with GH CLI
        run: |
          VERSION=$(date +'%Y.%-m.%-d')
          gh release create "$VERSION"
          gh release upload "$VERSION" ./bin/Release/Okane.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

