name: Build and Publish Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Run Premake5 with VS2022
        run: premake5 vs2022

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Release with MSBuild
        run: |
          msbuild /p:Configuration=Release

      - name: Create Release with GH CLI
        shell: powershell
        run: |
          $date = Get-Date -Format 'yyyy.MM.dd'
          $env:VERSION = "$date"
          echo "VERSION=$(Get-Date -Format 'yyyy.MM.dd')" >> $GITHUB_ENV
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
          gh release create "$env:VERSION" --generate-notes
          gh release upload "$env:VERSION" bin/Release/Okane.exe