name: Build and Publish Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"

      - name: Run Premake5 with VS2022
        run: premake5 vs2022

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Release with MSBuild
        run: |
          msbuild /p:Configuration=Release

      - name: Create Release with GH CLI
        shell: powershell
        run: |
          $date = Get-Date -Format 'yyyy.M.d'
          $env:VERSION = "$date"
          echo "VERSION=$(Get-Date -Format 'yyyy.M.d')" >> $GITHUB_ENV
          gh release create "$env:VERSION" --generate-notes
          gh release upload "$env:VERSION" bin/Release/Okane.exe

      - name: Download wingetcreate and publish to winget
        shell: powershell
        run: |
          $date = Get-Date -Format 'yyyy.M.d'
          $env:VERSION = "$date"
          echo "VERSION=$(Get-Date -Format 'yyyy.M.d')" >> $GITHUB_ENV

          $url = "https://github.com/Paulanerus/Okane/releases/download/$env:VERSION/Okane.exe"

          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Paulanerus.Okane -s -v "$env:VERSION" -u $url -t "${{ secrets.OKANE_WINGET }}""

  source:
    needs: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Package files
        run: |
          tar -czvf Source.tar.gz --exclude=.git --exclude=.github --exclude=.gitignore --exclude=.gitmodules ./src ./LICENSE.md ./premake5.lua ./README.md ./libs/rang/include/rang.hpp
          gh release upload $(date +'%Y.%-m.%-d') Source.tar.gz
